rem 	execute from SRC directory.  The file should not be moved!

call qsave Menu.f
call qsave Keysave.f
call qsave builtby.f
call qsave Dialog.f
call qsave BUTTON.F
call qsave CONTROLS.F
call qsave CONTROL.F
call qsave WINMSG.F
call qsave CHILDWND.F
call qsave Window.f
call qsave GENERIC.F
call qsave Dc.f
call qsave FONTS.F
call qsave COLORS.F
call qsave CLASSDBG.F
call qsave FLOAT.F
call qsave DIS486.F
call qsave ASMWIN32.F
call qsave ASMMAC.F
call qsave 486ASM.F
call qsave EXCEPTIO.F
call qsave DBGSRC2.F
call qsave Utils.f
call qsave LINEEDIT.F
call qsave ENVIRON.F
call qsave MAPFILE.F
call qsave KEYBOARD.F
call qsave ANSFILE.F
call qsave REGISTRY.F
call qsave SCRNCTRL.F
call qsave Class.f
call qsave WORDS.F
call qsave CALLBACK.F
call qsave Winlib.f
call qsave IID.F
call qsave Later.f
call qsave BUILD.F
call qsave Debug.f
call qsave SEE.F
call qsave PRIMHASH.F
call qsave ASSERT.F
call qsave Fcases.f
call qsave TRANSIT.F
call qsave RESFORTH.H
call qsave INTERPIF.F
call qsave CTYPE.F
call qsave MODULE.F
call qsave Order.f
call qsave DTHREAD.F
call qsave DBGSRC1.F
call qsave POINTER.F
call qsave Nforget.f
call qsave Primutil.f
call qsave Version.f
call qsave Meta.f
call qsave Fkernel.f
call qsave Forthdlg.f
call qsave Extend.f

