#define IDD_FONTDLG                 100
#define IDD_FONT                    101
#define IDD_CHECK                   103
#define IDD_TEXT                    104
#define IDD_ABOUT_FORTH             700
#define IDD_ABOUT_TEXT              701
#define IDD_ABOUT_TEXT2             702
#define IDD_SAVE_MEMORY             200
#define IDD_AVAIL                   202
#define IDD_AVAIL_MEMORY            203
#define IDD_PAGEUP                  300
#define IDD_2UP                     302
#define IDD_4UP                     303
#define IDD_TITLE_TEXT              400
#define IDD_EDIT_TEXT               401
#define IDD_PROMPT_TEXT             404
#define IDD_EDIT_DIALOG             500
#define IDB_OPTION                  501
#define IDD_REPLACE_DIALOG          600
#define IDD-PROMPT_TEXT2            601
#define IDD_EDIT_TEXT2              602
#define IDD_EDIT2_DIALOG            800
#define IDD-PROMPT2_TEXT            801
#define IDD_EDIT2_TEXT              802
#define IDOK2                       803
#define IDD_PROMPT2_TEXT            804
#define IDOK3                       805
#define IDD_AVAIL_APPMEMORY         204
#define IDD_AVAIL_SYSMEMORY         205
#define IDD_START_ADDRESS           208
