#define ID_FILELIST                 102
#define ID_CURRENTFILE              104
#define ID_DIRECTORY                105
#define ID_MASK                     106
#define ID_OPEN                     107
#define IDD_SEARCHINFILES           100
#define ID_SEARCHTEXT               108
#define ID_FILECOUNT                113
#define ID_LINETEXT                 114
#define ID_CASE                     115
#define IDD_SIZE                    200
#define ID_TEXTSIZE                 201
#define ID_FONT                     202
#define ID_TEXTFONT                 203
#define IDD_OPTIONS                 300
#define ID_AUTOSAVE                 301
#define ID_PROMPT                   302
#define ID_OPENPROMPT               303
#define IDB_AUTOSAVE                304
#define IDB_OPENPROMPT              305
#define IDE_EXT                     306
#define IDB_SAVEFIND                309
#define IDB_TOOLBAR                 308
#define IDE_WRAP                    310
#define IDB_SAVEMARGIN              312
#define IDD_FILES                   400
#define IDL_FILES                   401
#define IDE_PATH                    313
#define ID_SUBDIR                   112
#define IDE_TAB                     317
#define IDE_MIN                     320
#define IDE_LPI                     321
#define IDB_STEP                    501
#define IDB_NEST                    502
#define IDB_UNEST                   503
#define IDB_CONT                    504
#define IDB_JUMP                    505
#define IDB_DONE                    506
#define IDB_PROC                    507
#define IDB_HERE                    508
#define IDD_DEBUG                   600
#define IDL_STACK                   601
#define IDR_DECIMAL                 603
#define IDR_HEX                     604
#define IDL_RETURN                  607
#define IDL_WORDS                   609
#define IDT_NAME                    610
#define IDB_INQUIRE                 605
#define IDT_RESULT                  606
#define IDB_BORDER                  323
#define IDE_COLS                    325

#define IDB_PAGELINES               327
#define ID_ALLOCCUR                 116
#define IDB_WEB                     328
#define IDB_CONSOLE                 330
#define IDE_CONLINES                331
#define IDB_FULL                    334
